### ISSUE TITLE
Setting ERDDAP_MIN/MAX_MEMORY in docker-compose does not appear to have any effect

### ISSUE THREAD

**Issue by joefutrelle** [axiom-data-science/docker-erddap#45]
Here's a fragment of my docker-compose file:

```yaml
  erddap:
    image: axiom/docker-erddap:2.14
    container_name: erddap
    environment:
      - ERDDAP_MIN_MEMORY=4G
      - ERDDAP_MAX_MEMORY=8G
```

Inside the container, I observe that the environment variables are not set as expected and that the Java options for min and max memory upon startup are both the fallback value of 4G. This indicates to me that I'm probably doing something wrong in docker-compose, because if I just `docker run` ERDDAP with the `--env` option everything works as expected. Any ideas?

**Comment by abkfenris** [comment]
Does that still occur if you specify your environment as an object rather than an array?

```yaml
  erddap:
    image: axiom/docker-erddap:2.14
    container_name: erddap
    environment:
      ERDDAP_MIN_MEMORY: 4G
      ERDDAP_MAX_MEMORY: 8G
```

**Comment by joefutrelle** [comment]
Yes, I'm still not seeing the variables set in the container.

**Comment by joefutrelle** [comment]
Interestingly, other environment variables I set in my compose file _are_ getting passed through (I tried `FOO=bar`).

**Comment by abkfenris** [comment]
Hmm, with

```yaml
version: "3.7"

services:
  erddap:
    image: axiom/docker-erddap:2.14
    container_name: erddap
    environment:
      ERDDAP_MIN_MEMORY: 4G
      ERDDAP_MAX_MEMORY: 8G
```
I can see the environment variables set.

```sh
➜ docker compose exec erddap env
PATH=/usr/local/tomcat/bin:/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=4bb7a9a14ca6
TERM=xterm
ERDDAP_MIN_MEMORY=4G
ERDDAP_MAX_MEMORY=8G
JAVA_HOME=/usr/local/openjdk-8
LANG=C.UTF-8
JAVA_VERSION=8u312
CATALINA_HOME=/usr/local/tomcat
TOMCAT_NATIVE_LIBDIR=/usr/local/tomcat/native-jni-lib
LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib
GPG_KEYS=05AB33110949707C93A279E3D3EFE6B686867BA6 07E48665A34DCAFAE522E5E6266191C37C037D42 47309207D818FFD8DCD3F83F1931D684307A10A5 541FBE7D8F78B25E055DDEE13C370389288584E7 5C3C5F3E314C866292F359A8F3AD5C94A67F707E 765908099ACF92702C7D949BFA0C35EA8AA299F1 79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED 9BA44C2621385CB966EBA586F72C284D731FABEE A27677289986DB50844682F8ACB77FC2E86E29AC A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23
TOMCAT_MAJOR=8
TOMCAT_VERSION=8.5.73
TOMCAT_SHA512=4d33760d007acc5271ba0f946d2be96f6146d4632e411c9b72d351fc49d08355e8b84b051713a2f580e0f633cbe4409b7e9bb0e62f3af8d1094c6e4b3fdb96f0
GOSU_VERSION=1.12
ERDDAP_VERSION=2.14
ERDDAP_CONTENT_URL=https://github.com/BobSimons/erddap/releases/download/v2.14/erddapContent.zip
ERDDAP_WAR_URL=https://github.com/BobSimons/erddap/releases/download/v2.14/erddap.war
ERDDAP_DATA=/erddapData
HOME=/root
```

Have you made sure to `docker compose down` between changes and builds? 

I've found the latest version of docker compose seems to not always adjust to changes in the config or image builds in `docker compose up` the same way that the previous generation of `docker-compose` did.
